#!/usr/bin/env python3
"""
init-hooks manage.py — 钩子注册表管理主入口

用法:
    python3 manage.py install          首次安装，注入 post-init.sh / 容器启动脚本
    python3 manage.py list             列出所有钩子
    python3 manage.py add ...          新增钩子
    python3 manage.py show <id>        查看钩子详情
    python3 manage.py edit <id> ...    修改钩子
    python3 manage.py enable <id>      启用
    python3 manage.py disable <id>     禁用
    python3 manage.py delete <id>      删除（需确认）
    python3 manage.py run [id]         立即执行（全部 or 指定id）
    python3 manage.py status           查看安装状态
"""

import json
import os
import sys
import subprocess
import shutil
import urllib.request
import zipfile
import tarfile
from datetime import datetime, timezone, timedelta
from pathlib import Path
from typing import Optional

# ── 路径常量 ──────────────────────────────────────────────────────────
HOME         = Path.home()
HOOKS_DIR    = HOME / ".openclaw" / "workspace" / ".init-hooks"
HOOKS_JSON   = HOOKS_DIR / "hooks.json"
DISPATCHER   = HOOKS_DIR / "dispatcher.sh"
LOG_FILE     = HOOKS_DIR / "last-run.log"
DOWNLOAD_DIR = HOOKS_DIR / "downloads"

POST_INIT    = HOME / ".openclaw" / "workspace" / "scripts" / "post-init.sh"
# 容器启动脚本路径：不同部署环境不一样（K8s 常见 /app/start.sh）。
# 用 INIT_HOOKS_START_SH 覆盖；本地无此文件时注入会静默跳过（属正常）。
START_SH     = Path(os.environ.get("INIT_HOOKS_START_SH", "/app/start.sh")).expanduser()

DISPATCHER_MARKER = "# init-hooks dispatcher"

CST = timezone(timedelta(hours=8))


def now_str() -> str:
    return datetime.now(CST).isoformat(timespec="seconds")


def _expand_path(p: str) -> str:
    """展开路径：支持 ~ 和 $HOME，统一转为绝对路径字符串。"""
    # 先替换 $HOME，再走 expanduser
    expanded = p.replace("$HOME", str(HOME))
    return str(Path(expanded).expanduser())


def _sh_dq(s: str) -> str:
    """转义字符串以安全嵌入 bash 双引号上下文。

    防止 hook name 里的 " / ` / $ / \\ 破坏生成的 dispatcher.sh 语法
    或触发命令注入（C1）。返回值不含外层引号，调用方自行加 "..."。
    """
    return (
        s.replace("\\", "\\\\")
         .replace('"', '\\"')
         .replace("`", "\\`")
         .replace("$", "\\$")
    )


# ── hooks.json 读写 ────────────────────────────────────────────────────
def load_hooks() -> dict:
    if not HOOKS_JSON.exists():
        return {"version": 1, "hooks": []}
    try:
        with open(HOOKS_JSON) as f:
            return json.load(f)
    except json.JSONDecodeError as e:
        print(f"❌ hooks.json 格式损坏，无法解析: {e}")
        print(f"   文件路径: {HOOKS_JSON}")
        print(f"   请手动检查或删除该文件后重新执行 install")
        sys.exit(1)
    except OSError as e:
        print(f"❌ 读取 hooks.json 失败: {e}")
        sys.exit(1)


def save_hooks(data: dict):
    HOOKS_DIR.mkdir(parents=True, exist_ok=True)
    try:
        with open(HOOKS_JSON, "w") as f:
            json.dump(data, f, ensure_ascii=False, indent=2)
    except OSError as e:
        print(f"❌ 写入 hooks.json 失败: {e}")
        print(f"   请检查磁盘空间和目录权限: {HOOKS_DIR}")
        sys.exit(1)


def next_id(data: dict) -> int:
    if not data["hooks"]:
        return 1
    return max(h["id"] for h in data["hooks"]) + 1


def next_order(data: dict) -> int:
    if not data["hooks"]:
        return 10
    return max(h["order"] for h in data["hooks"]) + 10


def get_hook(data: dict, hook_id: int) -> Optional[dict]:
    for h in data["hooks"]:
        if h["id"] == hook_id:
            return h
    return None


def _clean_hook_fields(h: dict):
    """切换 type 时清理不属于新 type 的旧字段，保持数据干净。"""
    htype = h.get("type", "inline")
    if htype == "inline":
        h.pop("path", None)
        h.pop("url", None)
        h.pop("entry", None)
    elif htype in ("script", "python"):
        if h.get("url"):
            h.pop("path", None)
            h.pop("content", None)
        else:
            h.pop("url", None)
            h.pop("entry", None)
            h.pop("content", None)


# ── dispatcher.sh 生成 ────────────────────────────────────────────────
def generate_dispatcher(data: dict):
    HOOKS_DIR.mkdir(parents=True, exist_ok=True)
    enabled = sorted(
        [h for h in data["hooks"] if h.get("enabled", True)],
        key=lambda x: x["order"]
    )

    lines = [
        "#!/usr/bin/env bash",
        "# AUTO-GENERATED by init-hooks skill — DO NOT EDIT MANUALLY",
        f"# Last updated: {now_str()}",
        "",
        "set +e",
        f'LOG_FILE="{LOG_FILE}"',
        f'DOWNLOAD_DIR="{DOWNLOAD_DIR}"',
        'mkdir -p "$DOWNLOAD_DIR"',
        'mkdir -p "$(dirname "$LOG_FILE")"',
        'echo "[init-hooks] ===== 启动时间: $(date) =====" | tee -a "$LOG_FILE"',
        "_HOOKS_SUCCESS=()",
        "_HOOKS_FAILED=()",
        "",
        "# ── 内置下载函数（CDN URL 钩子）────────────────────────────────",
        "_ih_download() {",
        '  local url="$1" dest="$2"',
        '  if [ -f "$dest" ]; then return 0; fi',
        '  echo "[init-hooks] 下载 $url ..." | tee -a "$LOG_FILE"',
        '  if command -v curl &>/dev/null; then',
        '    curl -fsSL "$url" -o "$dest" 2>> "$LOG_FILE"',
        '  elif command -v wget &>/dev/null; then',
        '    wget -q "$url" -O "$dest" 2>> "$LOG_FILE"',
        '  else',
        '    echo "[init-hooks] ❌ 无 curl/wget，无法下载" | tee -a "$LOG_FILE"; return 1',
        '  fi',
        "}",
        "",
        "# ── 内置解压函数 ─────────────────────────────────────────────────",
        "_ih_extract() {",
        '  local archive="$1" dest_dir="$2" entry="$3" suffix="$4" hook_id="$5"',
        '  mkdir -p "$dest_dir"',
        '  case "$archive" in',
        '    *.zip)             unzip -o -q "$archive" -d "$dest_dir" 2>> "$LOG_FILE" ;;',
        '    *.tar.gz|*.tgz)   tar -xzf "$archive" -C "$dest_dir" 2>> "$LOG_FILE" ;;',
        '    *.tar.bz2)        tar -xjf "$archive" -C "$dest_dir" 2>> "$LOG_FILE" ;;',
        '    *)                 cp "$archive" "$dest_dir/hook_${hook_id}.${suffix}" ;;',
        '  esac',
        '  local final="$DOWNLOAD_DIR/hook_${hook_id}.${suffix}"',
        '  local ep',
        '  if [ -n "$entry" ]; then',
        '    ep=$(find "$dest_dir" -type f -name "$entry" | head -1)',
        '  else',
        '    ep=$(find "$dest_dir" -type f -name "*.${suffix}" | head -1)',
        '  fi',
        '  if [ -z "$ep" ]; then',
        '    echo "[init-hooks] ❌ 压缩包内找不到 .${suffix} 入口" | tee -a "$LOG_FILE"; return 1',
        '  fi',
        '  ln -sf "$(realpath "$ep")" "$final" && chmod +x "$ep"',
        "}",
        "",
    ]

    for h in enabled:
        hid   = h["id"]
        name  = h["name"]
        name_sh = _sh_dq(name)   # C1: 转义后再嵌入 bash 双引号上下文
        htype = h.get("type", "inline")
        suffix = "py" if htype == "python" else "sh"
        url   = h.get("url", "")
        entry = h.get("entry", "")

        lines.append(f'echo "[init-hooks] ▶ #{hid} {name_sh}..." | tee -a "$LOG_FILE"')

        if url:
            # CDN URL 钩子：先下载解压，再执行
            archive_var = f'"$DOWNLOAD_DIR/hook_{hid}_archive"'
            dest_dir_var = f'"$DOWNLOAD_DIR/hook_{hid}"'
            final_var   = f'"$DOWNLOAD_DIR/hook_{hid}.{suffix}"'
            run_cmd = f'python3 {final_var}' if htype == "python" else f'bash {final_var}'
            lines += [
                f'_ih_download "{url}" {archive_var} &&',
                f'_ih_extract {archive_var} {dest_dir_var} "{entry}" "{suffix}" "{hid}"',
                f'if [ -f {final_var} ] && {run_cmd} >> "$LOG_FILE" 2>&1; then',
            ]
        elif htype == "inline":
            content = h.get("content", "")
            escaped = content.replace("'", "'\\''")
            lines.append(f"if bash -c '{escaped}' >> \"$LOG_FILE\" 2>&1; then")
        elif htype == "script":
            path = _expand_path(h.get("path", ""))
            lines.append(f'if bash "{path}" >> "$LOG_FILE" 2>&1; then')
        elif htype == "python":
            path = _expand_path(h.get("path", ""))
            lines.append(f'if python3 "{path}" >> "$LOG_FILE" 2>&1; then')
        else:
            lines.append(f'echo "[init-hooks] ⚠️ 未知类型 {htype}" | tee -a "$LOG_FILE"')
            continue

        lines.append(f'    _HOOKS_SUCCESS+=("#{hid} {name_sh}")')
        lines.append(f'    echo "[init-hooks] ✅ #{hid} 成功" | tee -a "$LOG_FILE"')
        lines.append("else")
        lines.append(f'    _HOOKS_FAILED+=("#{hid} {name_sh}")')
        lines.append(f'    echo "[init-hooks] ❌ #{hid} 失败" | tee -a "$LOG_FILE"')
        lines.append("fi")
        lines.append("")

    lines += [
        'echo "" | tee -a "$LOG_FILE"',
        'echo "[init-hooks] ===== 执行摘要 =====" | tee -a "$LOG_FILE"',
        'echo "[init-hooks] ✅ 成功 (${#_HOOKS_SUCCESS[@]}): ${_HOOKS_SUCCESS[*]:-无}" | tee -a "$LOG_FILE"',
        'echo "[init-hooks] ❌ 失败 (${#_HOOKS_FAILED[@]}): ${_HOOKS_FAILED[*]:-无}" | tee -a "$LOG_FILE"',
        'echo "[init-hooks] 日志已写入: $LOG_FILE"',
    ]

    try:
        with open(DISPATCHER, "w") as f:
            f.write("\n".join(lines) + "\n")
        DISPATCHER.chmod(0o755)
    except OSError as e:
        print(f"[init-hooks] ❌ 生成 dispatcher.sh 失败: {e}")
        print(f"   请检查目录权限: {HOOKS_DIR}")
        sys.exit(1)


# ── 安装 ──────────────────────────────────────────────────────────────
def cmd_install():
    HOOKS_DIR.mkdir(parents=True, exist_ok=True)
    DOWNLOAD_DIR.mkdir(parents=True, exist_ok=True)

    # I2: 检查是否在 workspace 挂载路径下
    workspace = HOME / ".openclaw" / "workspace"
    if not workspace.exists():
        print(f"[init-hooks] ⚠️  workspace 目录不存在: {workspace}")
        print(f"[init-hooks]    钩子数据将写入 {HOOKS_DIR}，但可能不会持久化")
    else:
        print(f"[init-hooks] ✅ workspace 路径: {workspace}")

    if not HOOKS_JSON.exists():
        save_hooks({"version": 1, "hooks": []})
        print("[init-hooks] ✅ hooks.json 已初始化")
    else:
        print("[init-hooks] hooks.json 已存在，跳过初始化")

    generate_dispatcher(load_hooks())
    print(f"[init-hooks] ✅ dispatcher.sh 已生成: {DISPATCHER}")

    _inject_post_init()
    _inject_start_sh()

    print("\n[init-hooks] 🎉 安装完成！")
    print(f"  钩子目录: {HOOKS_DIR}")
    print(f"  添加钩子: python3 manage.py add --name '名称' --type inline --content '命令'")
    print(f"  查看列表: python3 manage.py list")


def _inject_post_init():
    if POST_INIT.exists():
        content = POST_INIT.read_text()
        if DISPATCHER_MARKER in content:
            print("[init-hooks] post-init.sh 已注入，跳过")
            return
        try:
            with open(POST_INIT, "a") as f:
                f.write(
                    f'\n{DISPATCHER_MARKER}\n'
                    f'_INIT_HOOKS_DISPATCHER="$HOME/.openclaw/workspace/.init-hooks/dispatcher.sh"\n'
                    f'if [ -f "$_INIT_HOOKS_DISPATCHER" ]; then'
                    f' bash "$_INIT_HOOKS_DISPATCHER" || echo "[post-init] init-hooks dispatcher failed"; fi\n'
                    f'unset _INIT_HOOKS_DISPATCHER\n'
                )
            print("[init-hooks] ✅ post-init.sh 已注入 dispatcher 调用")
        except OSError as e:
            print(f"[init-hooks] ❌ 注入 post-init.sh 失败: {e}")
            print(f"   请检查文件权限: {POST_INIT}")
    else:
        POST_INIT.parent.mkdir(parents=True, exist_ok=True)
        POST_INIT.write_text(
            '#!/usr/bin/env bash\n'
            '# post-init.sh — managed by init-hooks skill\n'
            f'{DISPATCHER_MARKER}\n'
            '_INIT_HOOKS_DISPATCHER="$HOME/.openclaw/workspace/.init-hooks/dispatcher.sh"\n'
            'if [ -f "$_INIT_HOOKS_DISPATCHER" ]; then'
            ' bash "$_INIT_HOOKS_DISPATCHER" || echo "[post-init] init-hooks dispatcher failed"; fi\n'
            'unset _INIT_HOOKS_DISPATCHER\n'
        )
        POST_INIT.chmod(0o755)
        print("[init-hooks] ✅ post-init.sh 已创建并写入 dispatcher 调用")


def _inject_start_sh():
    # C2: start.sh 注入失败是正常情况，明确提示
    if not START_SH.exists():
        print(f"[init-hooks] ℹ️  {START_SH} 不存在，跳过（dispatcher 经由 post-init.sh 调用，正常）")
        return

    content = START_SH.read_text()
    POST_INIT_MARKER  = "# post-init hook"
    INIT_HOOKS_MARKER = "# init-hooks-direct hook"

    # U4: 同时检查 post-init.sh 里是否真的有 dispatcher 注入
    if POST_INIT_MARKER in content and POST_INIT.exists():
        if DISPATCHER_MARKER in POST_INIT.read_text():
            print("[init-hooks] ✅ start.sh 已有 post-init hook，dispatcher 经由 post-init.sh 间接调用")
            return

    if INIT_HOOKS_MARKER in content:
        print("[init-hooks] ✅ start.sh 已注入 init-hooks hook，跳过")
        return

    rel = ".openclaw/workspace/.init-hooks/dispatcher.sh"
    inject = (
        f"\n{INIT_HOOKS_MARKER}\n"
        f'_IH_DISPATCHER="$HOME/{rel}"\n'
        f'if [ -f "$_IH_DISPATCHER" ]; then bash "$_IH_DISPATCHER" || echo "[start.sh] init-hooks dispatcher failed"; fi\n'
        f'unset _IH_DISPATCHER\n'
    )
    try:
        with open(START_SH, "a") as f:
            f.write(inject)
        print("[init-hooks] ✅ start.sh 已注入 dispatcher 调用")
    except PermissionError:
        print("[init-hooks] ℹ️  start.sh 无写权限（正常情况），dispatcher 通过 post-init.sh 调用，无需额外操作")
    except OSError as e:
        print(f"[init-hooks] ⚠️  start.sh 写入失败: {e}")


# ── 列表 ──────────────────────────────────────────────────────────────
def cmd_list():
    data = load_hooks()
    hooks = sorted(data["hooks"], key=lambda x: x["order"])
    if not hooks:
        print("📋 暂无启动钩子。使用 `add` 命令添加。")
        return

    enabled_count = sum(1 for h in hooks if h.get("enabled", True))
    print(f"📋 启动钩子列表（按执行顺序，共 {len(hooks)} 个，{enabled_count} 个启用）\n")
    print(f"{'#':<4} {'名称':<22} {'类型':<8} {'顺序':<6} {'状态'}")
    print("─" * 58)
    for h in hooks:
        status = "✅ 启用" if h.get("enabled", True) else "⏸ 禁用"
        src    = "📎URL" if h.get("url") else "📄本地"
        print(f"#{h['id']:<3} {h['name']:<22} {h.get('type','inline'):<8} {h['order']:<6} {status}  {src}")
    print()


# ── 详情 ──────────────────────────────────────────────────────────────
def cmd_show(hook_id: int):
    data = load_hooks()
    h = get_hook(data, hook_id)
    if not h:
        print(f"❌ 钩子 #{hook_id} 不存在")
        sys.exit(1)

    print(f"\n📌 钩子 #{h['id']} 详情")
    print(f"  名称: {h['name']}")
    print(f"  类型: {h['type']}")
    print(f"  顺序: {h['order']}")
    print(f"  状态: {'✅ 启用' if h.get('enabled', True) else '⏸ 禁用'}")
    print(f"  创建: {h.get('created_at', '-')}")
    print(f"  更新: {h.get('updated_at', '-')}")
    if h.get("url"):   print(f"  URL:  {h['url']}")
    if h.get("entry"): print(f"  入口: {h['entry']}")
    if h.get("path"):  print(f"  路径: {h['path']}")
    if h.get("content"):
        print(f"  内容:\n---\n{h['content']}\n---")


# ── 新增 ──────────────────────────────────────────────────────────────
def cmd_add(args: list):
    """
    manage.py add --name "名称" --type inline --content "echo hi"
    manage.py add --name "名称" --type script --path "~/scripts/foo.sh"
    manage.py add --name "名称" --type python --path "~/scripts/foo.py"
    manage.py add --name "名称" --type script --url https://cdn.example.com/foo.zip --entry run.sh
    可追加 --order 30 指定顺序
    """
    import argparse
    p = argparse.ArgumentParser(prog="manage.py add")
    p.add_argument("--name",    required=True)
    p.add_argument("--type",    choices=["inline", "script", "python"], required=True)
    p.add_argument("--content", default="")
    p.add_argument("--path",    default="")
    p.add_argument("--url",     default="")
    p.add_argument("--entry",   default="", help="压缩包内入口文件（配合 --url 使用）")
    p.add_argument("--order",   type=int, default=0)
    ns = p.parse_args(args)

    data = load_hooks()
    hook: dict = {
        "id":         next_id(data),
        "name":       ns.name,
        "type":       ns.type,
        "enabled":    True,
        "order":      ns.order if ns.order > 0 else next_order(data),
        "created_at": now_str(),
        "updated_at": now_str(),
    }

    if ns.type == "inline":
        if not ns.content:
            print("❌ inline 类型需要 --content")
            sys.exit(1)
        hook["content"] = ns.content
    else:
        if ns.url:
            hook["url"]   = ns.url
            hook["entry"] = ns.entry
        elif ns.path:
            hook["path"] = ns.path  # 原样存储，generate_dispatcher 时 _expand_path 展开
        else:
            print(f"❌ {ns.type} 类型需要 --path 或 --url")
            sys.exit(1)

    data["hooks"].append(hook)
    save_hooks(data)
    generate_dispatcher(data)
    print(f"✅ 钩子 #{hook['id']} 已添加：{hook['name']}，dispatcher.sh 已重新生成")


# ── 修改 ──────────────────────────────────────────────────────────────
def cmd_edit(hook_id: int, args: list):
    import argparse
    p = argparse.ArgumentParser(prog=f"manage.py edit {hook_id}")
    p.add_argument("--name")
    p.add_argument("--type",    choices=["inline", "script", "python"])
    p.add_argument("--content")
    p.add_argument("--path")
    p.add_argument("--url")
    p.add_argument("--entry")
    p.add_argument("--order",   type=int, default=None)  # U2: 用 None 而非 0 区分"未传"
    ns = p.parse_args(args)

    data = load_hooks()
    h = get_hook(data, hook_id)
    if not h:
        print(f"❌ 钩子 #{hook_id} 不存在")
        sys.exit(1)

    if ns.name    is not None: h["name"]    = ns.name
    if ns.type    is not None: h["type"]    = ns.type
    if ns.content is not None: h["content"] = ns.content
    if ns.path    is not None: h["path"]    = ns.path
    if ns.url     is not None: h["url"]     = ns.url
    if ns.entry   is not None: h["entry"]   = ns.entry
    if ns.order   is not None: h["order"]   = ns.order  # U2: 0 也能正确写入

    # L3: 切换 type 后清理不属于新 type 的旧字段
    _clean_hook_fields(h)

    h["updated_at"] = now_str()
    save_hooks(data)
    generate_dispatcher(data)
    print(f"✅ 钩子 #{hook_id} 已更新，dispatcher.sh 已重新生成")


# ── 启用/禁用 ─────────────────────────────────────────────────────────
def cmd_enable(hook_id: int):
    _set_enabled(hook_id, True)


def cmd_disable(hook_id: int):
    _set_enabled(hook_id, False)


def _set_enabled(hook_id: int, enabled: bool):
    data = load_hooks()
    h = get_hook(data, hook_id)
    if not h:
        print(f"❌ 钩子 #{hook_id} 不存在")
        sys.exit(1)
    h["enabled"]    = enabled
    h["updated_at"] = now_str()
    save_hooks(data)
    generate_dispatcher(data)
    print(f"✅ 钩子 #{hook_id} 已{'启用' if enabled else '禁用'}，dispatcher.sh 已重新生成")


# ── 删除 ──────────────────────────────────────────────────────────────
def cmd_delete(hook_id: int, force: bool = False):
    data = load_hooks()
    h = get_hook(data, hook_id)
    if not h:
        print(f"❌ 钩子 #{hook_id} 不存在")
        sys.exit(1)

    if not force:
        print(f"⚠️  即将删除钩子 #{hook_id}: {h['name']}")
        if h.get("content"): print(f"   内容预览: {h['content'][:80]}")
        elif h.get("path"):  print(f"   路径: {h['path']}")
        elif h.get("url"):   print(f"   URL:  {h['url']}")
        try:
            answer = input("确认删除？(y/N): ").strip().lower()
        except EOFError:
            # U2: 非交互环境（无 stdin，如 agent 自动执行）不崩溃，安全拒绝
            print("ℹ️  非交互环境无法确认，已取消。如需直接删除请加 --force")
            return
        if answer != "y":
            print("已取消")
            return

    data["hooks"] = [x for x in data["hooks"] if x["id"] != hook_id]
    save_hooks(data)
    generate_dispatcher(data)
    print(f"✅ 钩子 #{hook_id} 已删除，dispatcher.sh 已重新生成")


# ── 运行 ──────────────────────────────────────────────────────────────
def cmd_run(hook_id: Optional[int] = None):
    if hook_id is not None:
        _run_single(hook_id)
    else:
        _run_dispatcher()


def _run_dispatcher():
    if not DISPATCHER.exists():
        print("❌ dispatcher.sh 不存在，请先执行 install")
        sys.exit(1)
    print("[init-hooks] 执行 dispatcher.sh...\n")
    try:
        sys.exit(subprocess.run(["bash", str(DISPATCHER)]).returncode)
    except FileNotFoundError:
        print("❌ 找不到 bash，请确认系统已安装 bash")
        sys.exit(1)
    except OSError as e:
        print(f"❌ 执行 dispatcher.sh 失败: {e}")
        sys.exit(1)


def _run_single(hook_id: int):
    data = load_hooks()
    h = get_hook(data, hook_id)
    if not h:
        print(f"❌ 钩子 #{hook_id} 不存在")
        sys.exit(1)

    print(f"[init-hooks] ▶ 运行钩子 #{hook_id}: {h['name']}\n")

    htype  = h.get("type", "inline")
    suffix = "py" if htype == "python" else "sh"

    # U3: URL 钩子复用与 dispatcher 一致的下载逻辑
    if h.get("url"):
        if not _download_hook(h):
            print("❌ 下载失败，中止执行")
            sys.exit(1)
        exec_path = str(DOWNLOAD_DIR / f"hook_{hook_id}.{suffix}")
        cmd = ["python3", exec_path] if htype == "python" else ["bash", exec_path]
    elif htype == "inline":
        cmd = ["bash", "-c", h.get("content", "")]
    elif htype in ("script", "python"):
        path = _expand_path(h.get("path", ""))
        cmd  = ["python3", path] if htype == "python" else ["bash", path]
    else:
        print(f"❌ 未知类型: {htype}")
        sys.exit(1)

    try:
        rc = subprocess.run(cmd).returncode
    except FileNotFoundError as e:
        print(f"❌ 找不到执行器: {e}")
        print(f"   命令: {' '.join(cmd)}")
        sys.exit(1)
    except OSError as e:
        print(f"❌ 执行钩子 #{hook_id} 失败: {e}")
        sys.exit(1)
    print(f"\n{'✅' if rc == 0 else '❌'} 钩子 #{hook_id} {'执行成功' if rc == 0 else f'执行失败（exit {rc}）'}")
    sys.exit(rc)


def _is_within(base: Path, target: Path) -> bool:
    """target 解析后是否仍在 base 目录内（防路径穿越）。"""
    try:
        base_r = base.resolve()
        target_r = (base / target).resolve() if not target.is_absolute() else target.resolve()
        return base_r == target_r or base_r in target_r.parents
    except OSError:
        return False


def _safe_extract_zip(zf: "zipfile.ZipFile", dest_dir: Path):
    """解压 zip，拒绝穿越到 dest_dir 之外的条目（I1）。"""
    for member in zf.namelist():
        if not _is_within(dest_dir, Path(member)):
            raise ValueError(f"压缩包含不安全路径（穿越）: {member}")
    zf.extractall(dest_dir)


def _safe_extract_tar(tf: "tarfile.TarFile", dest_dir: Path):
    """解压 tar，拒绝穿越/软链穿越条目（I1）。Python 3.12+ 用 data filter。"""
    for member in tf.getmembers():
        if not _is_within(dest_dir, Path(member.name)):
            raise ValueError(f"压缩包含不安全路径（穿越）: {member.name}")
        if member.issym() or member.islnk():
            if not _is_within(dest_dir, Path(member.linkname)):
                raise ValueError(f"压缩包含不安全链接: {member.name} → {member.linkname}")
    try:
        # Python 3.12+：data filter 额外拦截绝对路径/穿越/危险权限
        tf.extractall(dest_dir, filter="data")
    except TypeError:
        # 老版本无 filter 参数，已做手动 member 校验兜底
        tf.extractall(dest_dir)


def _download_hook(h: dict) -> bool:
    """下载 URL 钩子，解压后在 downloads/ 建立标准路径软链接。"""
    url     = h["url"]
    hook_id = h["id"]
    entry   = h.get("entry", "")
    htype   = h.get("type", "script")
    suffix  = "py" if htype == "python" else "sh"

    DOWNLOAD_DIR.mkdir(parents=True, exist_ok=True)
    dest_dir = DOWNLOAD_DIR / f"hook_{hook_id}"
    archive  = DOWNLOAD_DIR / f"hook_{hook_id}_archive"
    final    = DOWNLOAD_DIR / f"hook_{hook_id}.{suffix}"

    # 已有缓存直接返回
    if final.exists():
        return True

    print(f"[init-hooks] 下载 {url} ...")
    try:
        urllib.request.urlretrieve(url, str(archive))
    except Exception as e:
        print(f"❌ 下载失败: {e}")
        return False

    dest_dir.mkdir(parents=True, exist_ok=True)
    try:
        url_lower = url.lower()
        if url_lower.endswith(".zip") or zipfile.is_zipfile(str(archive)):
            with zipfile.ZipFile(str(archive)) as zf:
                _safe_extract_zip(zf, dest_dir)
        elif any(url_lower.endswith(s) for s in (".tar.gz", ".tgz", ".tar.bz2", ".tar")):
            with tarfile.open(str(archive)) as tf:
                _safe_extract_tar(tf, dest_dir)
        else:
            # 直接当脚本
            shutil.copy(str(archive), str(final))
            final.chmod(0o755)
            archive.unlink(missing_ok=True)
            return True
    except Exception as e:
        print(f"❌ 解压失败: {e}")
        return False
    finally:
        archive.unlink(missing_ok=True)

    # 找入口文件（L1: 只认文件，排除同名目录）
    if entry:
        candidates = [c for c in dest_dir.rglob(entry) if c.is_file()]
    else:
        candidates = [c for c in dest_dir.rglob(f"*.{suffix}") if c.is_file()]

    if not candidates:
        print(f"❌ 压缩包内未找到可执行入口（entry='{entry or '*.'+suffix}'），请用 --entry 指定入口文件")
        return False

    entry_path = candidates[0].resolve()  # 绝对路径，symlink 重建后不失效
    if final.exists() or final.is_symlink():
        final.unlink()
    final.symlink_to(entry_path)
    entry_path.chmod(0o755)
    print(f"[init-hooks] 入口就绪: {final.name} → {entry_path}")
    return True


# ── 状态 ──────────────────────────────────────────────────────────────
def cmd_status():
    print("\n📊 init-hooks 状态\n")
    print(f"  钩子目录:   {HOOKS_DIR}  {'✅' if HOOKS_DIR.exists() else '❌ 不存在'}")
    print(f"  hooks.json: {HOOKS_JSON}  {'✅' if HOOKS_JSON.exists() else '❌ 不存在'}")
    print(f"  dispatcher: {DISPATCHER}  {'✅' if DISPATCHER.exists() else '❌ 不存在'}")
    print(f"  post-init:  {POST_INIT}  {'✅' if POST_INIT.exists() else '⚠️ 不存在'}")

    if POST_INIT.exists():
        injected = DISPATCHER_MARKER in POST_INIT.read_text()
        print(f"  dispatcher 注入 post-init: {'✅' if injected else '❌ 未注入（运行 install）'}")

    # U4: 同时检查 post-init.sh 是否真的有 dispatcher 注入
    if START_SH.exists():
        sc = START_SH.read_text()
        has_post_init  = "# post-init hook" in sc
        has_direct     = "# init-hooks-direct hook" in sc
        pi_has_dispatcher = POST_INIT.exists() and DISPATCHER_MARKER in POST_INIT.read_text()

        if has_direct:
            start_status = "✅ 直接注入"
        elif has_post_init and pi_has_dispatcher:
            start_status = "✅ 间接（via post-init.sh）"
        elif has_post_init and not pi_has_dispatcher:
            start_status = "⚠️  有 post-init hook 但 post-init.sh 未注入 dispatcher（运行 install）"
        else:
            start_status = "⚠️  未注入（无写权限属正常，post-init.sh 已覆盖）"
        print(f"  start.sh:   {start_status}")

    if LOG_FILE.exists():
        last = next((l for l in reversed(LOG_FILE.read_text().splitlines()) if "启动时间" in l), None)
        print(f"  上次运行: {last or '未知'}")

    data    = load_hooks()
    hooks   = data.get("hooks", [])
    enabled = sum(1 for h in hooks if h.get("enabled", True))
    print(f"  钩子数量: {len(hooks)} 个（{enabled} 个启用）\n")


# ── 主入口 ────────────────────────────────────────────────────────────
def _parse_id(raw: str) -> int:
    """把命令行 id 参数解析成 int；非法值给友好提示而非 ValueError traceback（U1）。"""
    try:
        return int(raw)
    except (ValueError, TypeError):
        print(f"❌ 无效的钩子 id: '{raw}'（应为数字，如 1、2、3）")
        print("   用 `python3 manage.py list` 查看现有钩子编号")
        sys.exit(1)


def main():
    args = sys.argv[1:]
    if not args:
        print(__doc__)
        sys.exit(0)

    cmd, rest = args[0], args[1:]

    if   cmd == "install": cmd_install()
    elif cmd == "list":    cmd_list()
    elif cmd == "show":
        if not rest: print("用法: manage.py show <id>"); sys.exit(1)
        cmd_show(_parse_id(rest[0]))
    elif cmd == "add":     cmd_add(rest)
    elif cmd == "edit":
        if not rest: print("用法: manage.py edit <id> [选项]"); sys.exit(1)
        cmd_edit(_parse_id(rest[0]), rest[1:])
    elif cmd == "enable":
        if not rest: print("用法: manage.py enable <id>"); sys.exit(1)
        cmd_enable(_parse_id(rest[0]))
    elif cmd == "disable":
        if not rest: print("用法: manage.py disable <id>"); sys.exit(1)
        cmd_disable(_parse_id(rest[0]))
    elif cmd == "delete":
        if not rest: print("用法: manage.py delete <id>"); sys.exit(1)
        force = "--force" in rest
        pos = next((x for x in rest if not x.startswith("--")), None)
        if pos is None: print("用法: manage.py delete <id> [--force]"); sys.exit(1)
        cmd_delete(_parse_id(pos), force=force)
    elif cmd == "run":
        hook_id = _parse_id(rest[0]) if rest and rest[0].lstrip("-").isdigit() else None
        cmd_run(hook_id)
    elif cmd == "status":  cmd_status()
    else:
        print(f"未知命令: {cmd}\n")
        print(__doc__)
        sys.exit(1)


if __name__ == "__main__":
    main()
